In [1]:
# Module 2: Data Cleaning & Feature Engineering

'''This module focuses on cleaning the raw social media dataset and
creating derived features such as engagement rate and viral score.
The processed dataset produced here is used by all downstream
modules including NLP, virality prediction, A/B testing, and forecasting.'''

'This module focuses on cleaning the raw social media dataset and\ncreating derived features such as engagement rate and viral score.\nThe processed dataset produced here is used by all downstream\nmodules including NLP, virality prediction, A/B testing, and forecasting.'

In [2]:
import pandas as pd
import numpy as np

In [3]:
DATA_PATH = "../data/processed/verified_raw_social_data.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,video_id,title,views,likes,comments,publish_date
0,WmW5E1bfuOg,Best Camera Phone देख कर Tourist हुए खुश 🤩#sh...,753007,36340,364,2026-01-17T09:04:21Z
1,I3e7Bh5a520,₹2.5 Lakh AI Dog vs Real Dog 🐕‍🦺#shorts,3787416,101512,436,2026-01-16T09:54:35Z
2,cDC-aloZLuk,iPhone 17 Pro Water Test Till DEAD😵,14094281,700215,5355,2026-01-14T08:15:11Z
3,PNWqGdb-Vic,नेता जी को मिला कमाल के Features वाला Phone vi...,1484665,64852,462,2026-01-13T12:31:20Z
4,oKYQqvkj-cM,Titanic Raise Reality 🤯 #shorts,1838683,96770,671,2026-01-11T13:11:43Z

In [4]:
print("Before cleaning:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Before cleaning:
Rows: 65
Columns: 6

In [5]:
df.isnull().sum()

video_id        0
title           0
views           0
likes           0
comments        0
publish_date    0
dtype: int64

In [15]:
# Fill numeric missing values with 0
numeric_cols = ["views", "likes", "comments"]
df[numeric_cols] = df[numeric_cols].fillna(0)

# Drop rows with missing titles or dates
df = df.dropna(subset=["title", "publish_date"])

In [7]:
df["views"] = df["views"].astype(int)
df["likes"] = df["likes"].astype(int)
df["comments"] = df["comments"].astype(int)

df["publish_date"] = pd.to_datetime(df["publish_date"])

In [8]:
# Engagement Rate
df["engagement_rate"] = (df["likes"] + df["comments"]) / df["views"]

# Handle division by zero
df["engagement_rate"] = df["engagement_rate"].replace([np.inf, np.nan], 0)

In [9]:
df["viral_score"] = (
    df["likes"] * 0.4 +
    df["comments"] * 0.6
)

In [10]:
df["publish_day"] = df["publish_date"].dt.day_name()
df["publish_hour"] = df["publish_date"].dt.hour

In [11]:
print("After cleaning:")
df.info()

After cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         65 non-null     object
 1   title            65 non-null     object
 2   views            65 non-null     int32
 3   likes            65 non-null     int32
 4   comments         65 non-null     int32
 5   publish_date     65 non-null     datetime64[ns, UTC]
 6   engagement_rate  65 non-null     float64
 7   viral_score      65 non-null     float64
 8   publish_day      65 non-null     object
 9   publish_hour     65 non-null     int32
dtypes: datetime64[ns, UTC](1), float64(2), int32(4), object(3)
memory usage: 4.2+ KB

In [12]:
df.head()

,video_id,title,views,likes,comments,publish_date,engagement_rate,viral_score,publish_day,publish_hour
0,WmW5E1bfuOg,Best Camera Phone देख कर Tourist हुए खुश 🤩#sh...,753007,36340,364,2026-01-17 09:04:21+00:00,0.048743,14754.4,Saturday,9
1,I3e7Bh5a520,₹2.5 Lakh AI Dog vs Real Dog 🐕‍🦺#shorts,3787416,101512,436,2026-01-16 09:54:35+00:00,0.026918,40866.4,Friday,9
2,cDC-aloZLuk,iPhone 17 Pro Water Test Till DEAD😵,14094281,700215,5355,2026-01-14 08:15:11+00:00,0.050061,283299.0,Wednesday,8
3,PNWqGdb-Vic,नेता जी को मिला कमाल के Features वाला Phone vi...,1484665,64852,462,2026-01-13 12:31:20+00:00,0.043992,26218.0,Tuesday,12
4,oKYQqvkj-cM,Titanic Raise Reality 🤯 #shorts,1838683,96770,671,2026-01-11 13:11:43+00:00,0.052995,39110.6,Sunday,13

In [13]:
OUTPUT_PATH = "../data/processed/processed_social_data.csv"
df.to_csv(OUTPUT_PATH, index=False)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [14]:
## Conclusion

'''In this module, raw social media data was cleaned, standardized,
and enriched with engagement and temporal features. The resulting
processed dataset enables advanced analytics such as sentiment
analysis, virality prediction, A/B testing, and trend forecasting.'''

'In this module, raw social media data was cleaned, standardized,\nand enriched with engagement and temporal features. The resulting\nprocessed dataset enables advanced analytics such as sentiment\nanalysis, virality prediction, A/B testing, and trend forecasting.'